Dev th genre and author ref
trevorhuis-smoothstack/LMS-Admin pull request #25
Opened 2020-05-11 23:10 UTC by trevorhuis-smoothstack

The toughest problem with the Book controller is the referential integrity to create the reference tables in the database. I decided to make these references with their own calls to be more flexible later. Maybe the orchestrator class can take the Genre, Author, and book to create and make the three separate calls. Otherwise we can pass a JSON request body with a book, author and genre all together

2020-05-11 23:32 UTC, justin-obrien-smoothstack commented
I think once the ORM is implemented, it will likely take care of the cross-referencing behind the scenes, provided we use the right annotations in our entities.

2020-05-11 23:53 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/AdminBookController.java
> +		if (book == null || book.getTitle().length() > 45)
We should also make sure the title is non-null here, since the schema doesn't allow books to have null titles.

2020-05-12 00:05 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/AdminGenreController.java
> +		if(genre == null || genre.getGenreName().length() > 45)
Might be checking the length of a null string here.

2020-05-12 00:06 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/AdminGenreController.java
> +		if(genre == null || genre.getGenreId() == null || genre.getGenreName().length() > 45)
Might be checking the length of a null string here.

2020-05-12 00:08 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/AdminBookController.java
> +        if (book == null || book.getTitle() == null || book.getTitle().length() > 45 || book.getPublisherId() == null)
The schema does allow a book to have a null publisher ID, but that doesn't mean our application necessarily has to allow it. For consistency, though, if a publisher ID is required here, it should also be required in the update method.

2020-05-12 00:08 UTC, justin-obrien-smoothstack requested changes
Looks pretty good, just a few minor changes I've requested in per-line comments.

2020-05-12 03:29 UTC, justin-obrien-smoothstack approved these changes
Everything looks good. Resolved the 1 merge conflict by keeping the version from the GenreController PR (which includes the null string check).

2020-05-13 02:59 UTC, sean-darsie approved these changes
Looks good. good error handling. If we need to we can resolve the referential stuff in the service and dao layers.

2020-05-13 03:00 UTC, merged

2020-05-13 03:02 UTC, sean-darsie commented
just merged and pulled it down. There was just one typo. ID should be Id in the controller since that was recently changed in the entity